# Generated by Django 3.0.2 on 2020-02-04 12:15

import Exercise.models
from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date_creation', models.DateField()),
                ('date_update', models.DateField()),
                ('state', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('To validate', 'To validate'), ('Validated', 'Validated'), ('Solved', 'Solved')], default=Exercise.models.State['A'], enum_class=Exercise.models.State, max_length=11)),
                ('category', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('CONSTRUCTION', 'CONSTRUCTION'), ('SPECIAL_EVENT', 'SPECIAL_EVENT'), ('INCIDENT', 'INCIDENT'), ('WEATHER_CONDITION', 'WEATHER_CONDITION'), ('ROAD_CONDITION', 'ROAD_CONDITION')], enum_class=Exercise.models.Category, max_length=17)),
            ],
        ),
    ]
